### ISSUE TITLE
Cannot read properties of undefined (reading '__H') in Deno Fresh

### ISSUE THREAD

**Issue by omar2205** [nanostores/preact#2]
I'm trying to use this in Deno Fresh

```
TypeError: Cannot read properties of undefined (reading '__H')
    at f (https://esm.sh/v89/preact@10.10.0/deno/hooks.js:2:186)
    at D (https://esm.sh/v89/preact@10.10.0/deno/hooks.js:2:320)
    at q (https://esm.sh/v89/preact@10.10.0/deno/hooks.js:2:289)
    at p (https://esm.sh/v89/@nanostores/preact@0.2.0/deno/preact.js:2:174)
    at Object.default (file:///[REDACTED]/islands/ProjectSources.tsx:54:13)
    at h (https://esm.sh/v87/preact-render-to-string@5.2.0/X-ZC9wcmVhY3RAMTAuOC4y/deno/preact-render-to-string.js:4:1003)
    at h (https://esm.sh/v87/preact-render-to-string@5.2.0/X-ZC9wcmVhY3RAMTAuOC4y/deno/preact-render-to-string.js:9:66)
    at h (https://esm.sh/v87/preact-render-to-string@5.2.0/X-ZC9wcmVhY3RAMTAuOC4y/deno/preact-render-to-string.js:4:1103)
    at h (https://esm.sh/v87/preact-render-to-string@5.2.0/X-ZC9wcmVhY3RAMTAuOC4y/deno/preact-render-to-string.js:4:7)
    at h (https://esm.sh/v87/preact-render-to-string@5.2.0/X-ZC9wcmVhY3RAMTAuOC4y/deno/preact-render-to-string.js:4:190)
```

**Comment by ai** [comment]
Sorry, I am not Deno Fresh user and I will need help with this issue. Please send PR if you will find the source.

**Comment by omar2205** [comment]
Not sure what the problem is. I tried writing the hook myself, and it worked without problems. But, if I use this package, it breaks.

```ts
import { listenKeys } from 'nanostores'
function useStore(store, opts = {}) {
  let [, forceRerender] = useState({})
  useEffect(() => {
    let batching: number|undefined, timer, unlisten

    let rerender = () => {
      if(!batching) {
        batching = 1
        timer = setTimeout(() => {
          batching = undefined
          forceRerender({})
        })
      }
    }
    if(opts.keys) {
      unlisten = listenKeys(store, opts.keys, rerender)
    } else {
      unlisten = store.listen(rerender)
    }

    return () => {
      unlisten()
      clearTimeout(timer)
    }
  }, [store, '' + opts.keys])

  return store.get()
}
```

**Comment by Casedy** [comment]
Same trouble with my integration. Copy paste code to local codebase (as above) works well.

**Comment by distolma** [comment]
Importing `preact-render-to-string` with an `external` query parameter works for me. `"preact-render-to-string": "https://esm.sh/preact-render-to-string@5.2.6?external=preact"`

**Comment by phunanon** [comment]
Using the hook written above worked for me, using this import map:
```html
<script type="importmap">
  {
    "imports": {
      "preact": "./preact.module.js",
      "preact/hooks": "./hooks.module.js",
      "preact/jsx-runtime": "./jsxRuntime.module.js",
      "nanostores": "https://esm.sh/nanostores@1.1.0",
      "@nanostores/preact": "https://esm.sh/@nanostores/preact@1.0.0"
    }
  }
</script>
```

I'm not using Deno Fresh, but rather just using TypeScript's compiler for compiling JSX.
